services:
  django:
    container_name: simple_lms
    build: . 
    command: sleep infinity
    volumes:
      - ./code:/code 
    ports:
      - "8001:8000" 
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=simplelms.settings
      - POSTGRES_DB=simple_lms
      - POSTGRES_USER=simple_user
      - POSTGRES_PASSWORD=simple_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  postgres:
    container_name: simple_db
    image: postgres:latest
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes: 
  postgres-data: